import { isCancel, log, note, select, spinner } from '@clack/prompts';
import { Command } from 'commander';
import { spawn } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { chmod, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { hostname, homedir, tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { findProjectRoot, loadEffectiveConfig, setConfigValue, unsetConfigValue } from '@agentbox/config';
import { DEFAULT_ENV_PATTERNS, projectSlugFromOriginUrl } from '@agentbox/sandbox-core';
import {
  pushPreparedToCustody,
  pushProjectSeedToCustody,
  readGitOriginUrl,
} from '@agentbox/sandbox-cloud';
import {
  drainCreateJobs,
  GitHubAppLeaser,
  loadGitHubAppConfig,
  parseGitRemote,
  PostgresStore,
  toAuthedHttpsUrl,
} from '@agentbox/relay';
import { randomBytes } from 'node:crypto';
import { providerForCreate } from '../provider/registry.js';
import { makeControlPlaneCreateBox } from '../control-plane/create-box.js';
import { runGitHubAppManifestFlow } from '../control-plane/github-app-manifest.js';
import { deployControlPlaneToVercel } from '../control-plane/deploy-vercel.js';
import { runHetznerDeploy } from '../control-plane/deploy-hetzner.js';
import { resolveHubAuthEnv } from '../control-plane/hub-auth-env.js';
import {
  addRepoUrl,
  checkRepoInstalled,
  loadControlPlaneMeta,
  openInBrowser,
  resolveOwnerRepo,
} from '../control-plane/ensure-repo-installed.js';
import {
  CustodyClient,
  collectAgentCredentialUploads,
  planPush,
  type UploadItem,
} from '../control-plane/custody-client.js';
import { ControlPlaneAdminClient } from '../control-plane/admin-client.js';
import { AGENT_SYNC_SPECS } from '@agentbox/sandbox-core';
import { handleLifecycleError } from './_errors.js';

const CP_DIR = join(homedir(), '.agentbox', 'control-plane');
const PEM_PATH = join(CP_DIR, 'github-app.pem');
const ENV_PATH = join(CP_DIR, 'control-plane.env');
const META_PATH = join(CP_DIR, 'control-plane.json');

/** Default GitHub repo the control plane is deployed from (Vercel + Hetzner). */
const DEFAULT_DEPLOY_REPO = 'madarco/agentbox';
const DEFAULT_DEPLOY_REF = 'main';

/** Persist `relay.controlPlaneUrl` and report it. Shared by set-url + setup. */
async function applyControlPlaneUrl(url: string): Promise<string> {
  const trimmed = url.replace(/\/$/, '');
  await setConfigValue('global', 'relay.controlPlaneUrl', trimmed, process.cwd());
  return trimmed;
}

/** Poll a deployed plane's /healthz until it answers (or the deadline elapses). */
async function waitForHealthz(url: string, deadlineMs: number): Promise<boolean> {
  const stop = Date.now() + deadlineMs;
  while (Date.now() < stop) {
    try {
      const res = await fetch(`${url}/healthz`, { signal: AbortSignal.timeout(8000) });
      if (res.ok) return true;
    } catch {
      /* retry */
    }
    await delay(4000);
  }
  return false;
}

/**
 * The hetzner hub-auth env block appended to `control-plane.env`. The full-hub
 * compose sets the profile literally, but these secrets (`BETTER_AUTH_SECRET`,
 * admin email/password) are read from the `.env` by the compose file, so a
 * network-reachable hub is login-gated.
 */
function hetznerAuthBody(hubAuth: {
  AGENTBOX_HUB_AUTH: string;
  BETTER_AUTH_SECRET: string;
  AGENTBOX_HUB_ADMIN_EMAIL: string;
  AGENTBOX_HUB_ADMIN_PASSWORD: string;
}): string {
  return (
    `AGENTBOX_HUB_PROFILE=hetzner\n` +
    `AGENTBOX_HUB_AUTH=${hubAuth.AGENTBOX_HUB_AUTH}\n` +
    `BETTER_AUTH_SECRET=${hubAuth.BETTER_AUTH_SECRET}\n` +
    `AGENTBOX_HUB_ADMIN_EMAIL=${hubAuth.AGENTBOX_HUB_ADMIN_EMAIL}\n` +
    `AGENTBOX_HUB_ADMIN_PASSWORD=${hubAuth.AGENTBOX_HUB_ADMIN_PASSWORD}\n`
  );
}

/**
 * Ensure `control-plane.env` carries the hub-auth block (a prior `setup --deploy
 * none` writes only the App creds). Appends it when `BETTER_AUTH_SECRET` is
 * absent; returns false only if the operator cancels the login prompt.
 */
async function ensureHetznerHubAuth(): Promise<boolean> {
  const body = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '';
  if (/^BETTER_AUTH_SECRET=/m.test(body)) return true;
  const hubAuth = await resolveHubAuthEnv();
  if (!hubAuth) return false;
  await writeFile(ENV_PATH, body + hetznerAuthBody(hubAuth), { mode: 0o600 });
  await chmod(ENV_PATH, 0o600);
  return true;
}

type DeployTarget = 'vercel' | 'hetzner' | 'none';

interface SetupOpts {
  name?: string;
  org?: string;
  deploy?: string;
  ref?: string;
  repo?: string;
}

const setupSub = new Command('setup')
  .description(
    'Create the GitHub App the control plane leases push tokens with, and write its deploy config (env + admin token)',
  )
  .option('--name <name>', 'GitHub App name (default: autogenerated agentbox-<rand>, must be globally unique)')
  .option('--org <org>', 'create the App under an organization instead of your user account')
  .option('--deploy <target>', 'deploy the plane after creating the App: vercel | hetzner | none')
  .option('--repo <owner/name>', 'GitHub repo to deploy the plane from (default madarco/agentbox; fork + pass this if you don\'t own it)')
  .option('--ref <ref>', 'git ref of the repo to deploy (branch/tag/sha; default main) — used by Vercel + Hetzner')
  .action(async (opts: SetupOpts) => {
    try {
      // Globally-unique by default — GitHub rejects duplicate App names.
      const name = opts.name ?? `agentbox-${randomBytes(4).toString('hex')}`;

      note(
        'Your browser will open to GitHub to create the App. Review the\n' +
          'permissions (Contents + Pull requests: write) and click "Create".',
        'GitHub App',
      );

      const s = spinner();
      s.start('waiting for the GitHub App to be created in your browser');
      const app = await runGitHubAppManifestFlow({
        appName: String(name),
        org: opts.org,
        // Honor GHES overrides (and make the flow scriptable in tests).
        githubUrl: process.env.GITHUB_URL,
        apiBaseUrl: process.env.GITHUB_API_URL,
        openBrowser: openInBrowser,
        log: (line) => s.message(line),
      });
      s.stop(`GitHub App created: ${app.slug} (id ${app.appId})`);

      // Persist the App key + a generated admin token as the plane's deploy env.
      const adminToken = randomBytes(32).toString('hex');
      await mkdir(CP_DIR, { recursive: true });
      await writeFile(PEM_PATH, app.pem, { mode: 0o600 });
      await chmod(PEM_PATH, 0o600);
      const pemB64 = Buffer.from(app.pem, 'utf8').toString('base64');
      const envBody =
        `# AgentBox control plane deploy env (generated by 'agentbox control-plane setup').\n` +
        `# Feed to docker compose (--env-file) or 'vercel env add'. Keep secret.\n` +
        `GITHUB_APP_ID=${app.appId}\n` +
        `GITHUB_APP_PRIVATE_KEY=${pemB64}\n` +
        `AGENTBOX_RELAY_ADMIN_TOKEN=${adminToken}\n`;
      await writeFile(ENV_PATH, envBody, { mode: 0o600 });
      await chmod(ENV_PATH, 0o600);
      await writeFile(
        META_PATH,
        JSON.stringify({ appId: app.appId, slug: app.slug, htmlUrl: app.htmlUrl, installUrl: app.installUrl }, null, 2) + '\n',
        { mode: 0o600 },
      );

      log.success(`GitHub App ready. Deploy config written to ${ENV_PATH} (0600).`);

      // --- Deploy step (after the App exists) ---
      const target = await resolveDeployTarget(opts.deploy);
      let deployedUrl: string | null = null;
      if (target !== 'none') {
        // Prompt for the hub login admin BEFORE the deploy spinner starts (a
        // spinner and @clack prompts can't share the terminal). Setting these
        // turns login on in the deployed hub so it is never left loginless — both
        // vercel and hetzner (the Caddy-HTTPS docker-compose deploy).
        const hubAuth = await resolveHubAuthEnv();
        // hetzner reads ENV_PATH (written to the VPS .env); append the auth env +
        // the Postgres auth profile so docker-compose enforces login there too.
        if (target === 'hetzner' && hubAuth) {
          await writeFile(ENV_PATH, envBody + hetznerAuthBody(hubAuth), { mode: 0o600 });
          await chmod(ENV_PATH, 0o600);
        }
        const ds = spinner();
        ds.start(`deploying the control plane to ${target}`);
        try {
          const onLog = (line: string): void => ds.message(line);
          const repo = opts.repo ?? DEFAULT_DEPLOY_REPO;
          const ref = opts.ref ?? DEFAULT_DEPLOY_REF;
          if (target === 'vercel') {
            const env = {
              GITHUB_APP_ID: app.appId,
              GITHUB_APP_PRIVATE_KEY: pemB64,
              AGENTBOX_RELAY_ADMIN_TOKEN: adminToken,
              ...(hubAuth ?? {}),
            };
            deployedUrl = (await deployControlPlaneToVercel({ env, repo, ref, log: onLog })).url;
          } else {
            deployedUrl = (await runHetznerDeploy({ envPath: ENV_PATH, repoRef: ref, log: onLog })).url;
          }
          ds.stop(`deployed: ${deployedUrl}`);
        } catch (e) {
          // Stop the spinner (code 1) before printing — otherwise it keeps
          // animating its last "creating the firewall…" frame under the error.
          ds.stop(`deploy to ${target} failed`, 1);
          log.warn(`deploy to ${target} failed: ${e instanceof Error ? e.message : String(e)}`);
          printManualDeploy();
        }
      } else {
        printManualDeploy();
      }

      if (deployedUrl) {
        const url = await applyControlPlaneUrl(deployedUrl);
        log.success(`Pointed the CLI at ${url} (relay.controlPlaneUrl).`);
        const ok = await waitForHealthz(url, 60_000);
        log[ok ? 'success' : 'warn'](
          ok ? `Control plane is healthy (${url}/healthz).` : `Could not confirm ${url}/healthz yet — check the deployment.`,
        );
      }

      // Open the repo-selection page so the user can authorize repos right away.
      log.info(`Install the App on your repos: ${app.installUrl}`);
      openInBrowser(app.installUrl);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

/** Resolve the deploy target from the flag, or ask interactively. */
async function resolveDeployTarget(flag: string | undefined): Promise<DeployTarget> {
  if (flag === 'vercel' || flag === 'hetzner' || flag === 'none') return flag;
  if (flag) {
    log.warn(`unknown --deploy "${flag}"; choose interactively`);
  }
  const choice = await select({
    message: 'Deploy the control plane now?',
    options: [
      { value: 'vercel', label: 'Vercel — managed (auto-provisions Neon Postgres)' },
      { value: 'hetzner', label: 'Hetzner VPS — HTTPS via <ip>.sslip.io + Caddy/Let’s Encrypt' },
      { value: 'none', label: 'Skip — I’ll deploy later (print manual steps)' },
    ],
    initialValue: 'vercel',
  });
  if (isCancel(choice)) return 'none';
  return choice as DeployTarget;
}

function printManualDeploy(): void {
  log.info(
    [
      'Deploy later with the written env:',
      `  Self-host:  cd apps/hub && docker compose --env-file ${ENV_PATH} up --build`,
      `  Vercel:     agentbox control-plane setup --deploy vercel  (or 'vercel env add' the vars + 'vercel deploy --prod')`,
      `  Then:       agentbox control-plane set-url https://<your-plane-url>`,
    ].join('\n'),
  );
}

const setUrlSub = new Command('set-url')
  .description('Point boxes + the CLI at a deployed control plane (sets relay.controlPlaneUrl)')
  .argument('<url>', 'base URL of the deployed control plane, e.g. https://plane.example.com')
  .action(async (url: string) => {
    try {
      const trimmed = await applyControlPlaneUrl(url);
      log.success(`Set relay.controlPlaneUrl = ${trimmed}`);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const unsetUrlSub = new Command('unset-url')
  .description('Stop using a control plane on this machine (removes relay.controlPlaneUrl)')
  .option('--purge', "also delete this machine's local App metadata + admin token (~/.agentbox/control-plane)")
  .action(async (opts: { purge?: boolean }) => {
    try {
      // set-url writes the global scope; also clear a per-project override if one
      // exists. A cwd with no project config just yields `existed:false` (the
      // project unset never throws for that) — real I/O/write errors from either
      // scope propagate to handleLifecycleError rather than being masked.
      const g = await unsetConfigValue('global', 'relay.controlPlaneUrl', process.cwd());
      const p = await unsetConfigValue('project', 'relay.controlPlaneUrl', process.cwd());
      if (!g.existed && !p.existed) {
        log.info('No control plane was configured (relay.controlPlaneUrl not set).');
      } else {
        const where = [g.existed ? 'global' : null, p.existed ? 'project' : null].filter(Boolean).join(' + ');
        log.success(
          `Removed relay.controlPlaneUrl (${where}). New cloud boxes now push through the host relay ` +
            '(your laptop must be on), and the GitHub-App repo-authorization prompt no longer fires.',
        );
      }
      if (existsSync(CP_DIR)) {
        if (opts.purge) {
          await rm(CP_DIR, { recursive: true, force: true });
          log.success(`Purged this machine's control-plane credentials (${CP_DIR}).`);
        } else {
          log.info(`This machine's App metadata + admin token remain in ${CP_DIR} (use --purge to delete).`);
        }
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

interface StatusOpts {
  url?: string;
  json?: boolean;
}

const statusSub = new Command('status')
  .description('Check whether the configured control plane is reachable')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--json', 'emit JSON')
  .action(async (opts: StatusOpts) => {
    try {
      const { loadEffectiveConfig } = await import('@agentbox/config');
      const cfg = await loadEffectiveConfig(process.cwd());
      const url = (opts.url ?? cfg.effective.relay.controlPlaneUrl ?? '').replace(/\/$/, '');
      if (!url) {
        log.error('No control plane configured. Run `agentbox control-plane set-url <url>` (or pass --url).');
        process.exitCode = 1;
        return;
      }
      let healthy = false;
      let detail = '';
      try {
        const res = await fetch(`${url}/healthz`, { signal: AbortSignal.timeout(8000) });
        healthy = res.ok;
        const body = (await res.json().catch(() => ({}))) as { boxes?: number; events?: number };
        detail = `${String(body.boxes ?? 0)} box(es), ${String(body.events ?? 0)} event(s)`;
      } catch (e) {
        detail = e instanceof Error ? e.name : String(e);
      }
      if (opts.json) {
        process.stdout.write(JSON.stringify({ url, healthy, detail }) + '\n');
        return;
      }
      process.stdout.write(
        [`control plane: ${healthy ? 'reachable' : 'UNREACHABLE'}`, `  url:    ${url}`, `  health: ${detail}`].join('\n') +
          '\n',
      );
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const addSub = new Command('add')
  .description("Authorize the current project's git repo on the control plane's GitHub App")
  .action(async () => {
    try {
      const cfg = await loadEffectiveConfig(process.cwd());
      const controlPlaneUrl = cfg.effective.relay.controlPlaneUrl;
      if (!controlPlaneUrl) {
        log.error('No control plane configured. Run `agentbox control-plane set-url <url>` first.');
        process.exitCode = 1;
        return;
      }
      const ownerRepo = await resolveOwnerRepo(process.cwd());
      if (!ownerRepo) {
        log.error('No git origin found here — `cd` into a project with a GitHub remote.');
        process.exitCode = 1;
        return;
      }
      const { owner, repo } = ownerRepo;
      const installed = await checkRepoInstalled(owner, repo, controlPlaneUrl);
      if (installed === true) {
        log.success(`${owner}/${repo} is already authorized on the GitHub App.`);
        return;
      }
      const url = addRepoUrl(loadControlPlaneMeta());
      if (!url) {
        log.error(
          'No GitHub App metadata found locally. Run this from a machine that ran `control-plane setup`,\n' +
            'or open your App settings on GitHub and add the repo manually.',
        );
        process.exitCode = 1;
        return;
      }
      log.info(`Opening ${url} — select ${owner}/${repo}, then approve.`);
      openInBrowser(url);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

/** Load the setup-written App creds into the env if not already set. */
function loadControlPlaneEnv(): void {
  if (process.env.GITHUB_APP_ID && process.env.GITHUB_APP_PRIVATE_KEY) return;
  if (!existsSync(ENV_PATH)) return;
  for (const line of readFileSync(ENV_PATH, 'utf8').split('\n')) {
    const m = /^([A-Z_]+)=(.*)$/.exec(line.trim());
    if (m && !process.env[m[1]!]) process.env[m[1]!] = m[2];
  }
}

/** Run `git <args>`, rejecting on a non-zero exit. */
function runGit(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn('git', args, { stdio: ['ignore', 'ignore', 'pipe'] });
    let err = '';
    child.stderr.on('data', (c: Buffer) => (err += c.toString('utf8')));
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve() : reject(new Error(`git ${args[0]} failed (${String(code)}): ${err.trim()}`)),
    );
  });
}

interface WorkerOpts {
  store: string;
  once?: boolean;
  pollInterval: string;
}

const workerSub = new Command('worker')
  .description(
    'Drain the control plane box-creation queue and provision real boxes (long-running; needs provider creds + the App key)',
  )
  .requiredOption('--store <url>', 'Postgres URL of the control plane (same store the plane uses)')
  .option('--once', 'drain the queue once and exit (default: loop)')
  .option('--poll-interval <ms>', 'poll interval when looping', '5000')
  .action(async (opts: WorkerOpts) => {
    try {
      loadControlPlaneEnv();
      const appCfg = loadGitHubAppConfig();
      if (!appCfg) {
        log.error('No GitHub App configured. Run `agentbox control-plane setup` first.');
        process.exitCode = 1;
        return;
      }
      const store = new PostgresStore({ connectionString: opts.store });
      await store.migrate();
      const leaser = new GitHubAppLeaser(appCfg);
      const cfg = await loadEffectiveConfig(process.cwd());

      const createBox = makeControlPlaneCreateBox({
        leaseRemoteUrl: async (repoUrl) => {
          const { path } = parseGitRemote(repoUrl);
          const [owner, repo] = path.replace(/\.git$/, '').split('/');
          if (!owner || !repo) throw new Error(`cannot derive owner/repo from ${repoUrl}`);
          const { token } = await leaser.leaseRepoToken(owner, repo);
          return toAuthedHttpsUrl(repoUrl, token);
        },
        cloneRepo: async (authedUrl, repoUrl, dest, branch) => {
          await runGit(branch ? ['clone', '--branch', branch, authedUrl, dest] : ['clone', authedUrl, dest]);
          // Scrub the leased token: leave the box pointing at the bare origin.
          await runGit(['-C', dest, 'remote', 'set-url', 'origin', repoUrl]);
        },
        createBox: async ({ workspacePath, name, provider, onLog }) => {
          const p = await providerForCreate({ flag: provider, config: cfg.effective });
          const created = await p.create({ workspacePath, name, projectRoot: workspacePath, onLog });
          return { id: created.record.id };
        },
        tmpDir: (jobId) => join(tmpdir(), `agentbox-cp-worker-${jobId}`),
        cleanup: (dir) => rm(dir, { recursive: true, force: true }),
        log: (line) => process.stdout.write(`agentbox-cp-worker: ${line}\n`),
      });

      const workerId = `worker-${hostname()}-${String(process.pid)}`;
      const interval = Number.parseInt(opts.pollInterval, 10) || 5000;
      let running = true;
      const stop = (): void => {
        running = false;
      };
      process.on('SIGINT', stop);
      process.on('SIGTERM', stop);
      process.stdout.write(`agentbox-cp-worker: draining create jobs as ${workerId}\n`);
      do {
        const n = await drainCreateJobs(store, createBox, workerId);
        if (n > 0) process.stdout.write(`agentbox-cp-worker: processed ${String(n)} job(s)\n`);
        if (opts.once) break;
        await delay(interval);
      } while (running);
      await store.close();
    } catch (err) {
      handleLifecycleError(err);
    }
  });

/**
 * Resolve the control-plane URL (`--url` > `relay.controlPlaneUrl`) and the
 * admin bearer (`AGENTBOX_RELAY_ADMIN_TOKEN` > the setup-written env file).
 * Returns null and prints an actionable error when either is missing.
 *
 * `quiet` suppresses those errors, for callers where a control box is optional
 * and its absence is a normal outcome rather than a user mistake (the recover
 * key fallback, the by-name auto-adopt hook).
 */
export async function resolveCustodyTarget(
  urlFlag: string | undefined,
  opts: { quiet?: boolean } = {},
): Promise<{ url: string; adminToken: string } | null> {
  const cfg = await loadEffectiveConfig(process.cwd());
  const url = (urlFlag ?? cfg.effective.relay.controlPlaneUrl ?? '').replace(/\/$/, '');
  if (!url) {
    if (!opts.quiet)
      log.error('No control plane configured. Run `agentbox control-plane set-url <url>` (or pass --url).');
    return null;
  }
  loadControlPlaneEnv();
  const adminToken = process.env.AGENTBOX_RELAY_ADMIN_TOKEN ?? '';
  if (!adminToken) {
    if (!opts.quiet)
      log.error(
        'No admin token available. Set AGENTBOX_RELAY_ADMIN_TOKEN, or run this from the machine that\n' +
          'ran `agentbox control-plane setup` (it writes the token to ~/.agentbox/control-plane).',
      );
    return null;
  }
  return { url, adminToken };
}

/**
 * Slug a project into a custody `projects/<slug>` key: `owner__repo`, else the
 * dir name.
 *
 * Delegates to the shared `projectSlugFromOriginUrl` — every producer and
 * consumer of the `projects/<slug>` scope MUST derive the same key from the same
 * origin, and a second local implementation is exactly how they drift apart. (It
 * did: this used to take the *first* two path segments unsanitized, while the
 * create path and the hub worker take the last two and sanitize — so for a
 * nested remote like `gitlab.com/group/subgroup/repo` a push landed under
 * `group__subgroup` while the worker looked in `subgroup__repo`.)
 */
async function projectSlug(explicit: string | undefined, projectRoot: string): Promise<string> {
  if (explicit) return explicit.replace(/[^A-Za-z0-9._-]/g, '-');
  const origin = await readGitOriginUrl(projectRoot).catch(() => undefined);
  const slug = origin ? projectSlugFromOriginUrl(origin) : null;
  if (slug) return slug;
  return basename(projectRoot).replace(/[^A-Za-z0-9._-]/g, '-') || 'project';
}

/** Upload a set of items with a hash-skip pass; logs one line per decision. */
async function pushItems(
  client: CustodyClient,
  items: UploadItem[],
  prefix: string,
  force: boolean,
): Promise<void> {
  if (items.length === 0) {
    log.info('Nothing to push.');
    return;
  }
  const manifest = await client.list(prefix);
  const plan = planPush(items, manifest, { force });
  let uploaded = 0;
  let skipped = 0;
  for (const item of items) {
    const decision = plan.find((d) => d.path === item.path)!;
    if (decision.action === 'skip') {
      skipped++;
      continue;
    }
    const res = await client.put(item.path, item.data);
    if (res.changed) uploaded++;
    else skipped++;
  }
  log.success(`Pushed ${String(uploaded)} item(s), skipped ${String(skipped)} unchanged.`);
}

const credentialsPushSub = new Command('push')
  .description('Push host agent-credential backups (claude/codex/opencode) to the control box custody store')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--agent <id>', 'push only one agent: claude | codex | opencode')
  .option('--force', 'upload even when the stored hash matches')
  .action(async (opts: { url?: string; agent?: string; force?: boolean }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const only = opts.agent as 'claude' | 'codex' | 'opencode' | undefined;
      if (opts.agent && !['claude', 'codex', 'opencode'].includes(opts.agent)) {
        log.error(`unknown --agent "${opts.agent}" (expected claude | codex | opencode)`);
        process.exitCode = 1;
        return;
      }
      const items = await collectAgentCredentialUploads(only);
      const client = new CustodyClient(target);
      await pushItems(client, items, 'agents', opts.force === true);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const credentialsPullSub = new Command('pull')
  .description('Pull agent-credential backups from the control box custody store into ~/.agentbox')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--agent <id>', 'pull only one agent: claude | codex | opencode')
  .action(async (opts: { url?: string; agent?: string }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      if (opts.agent && !['claude', 'codex', 'opencode'].includes(opts.agent)) {
        log.error(`unknown --agent "${opts.agent}" (expected claude | codex | opencode)`);
        process.exitCode = 1;
        return;
      }
      const client = new CustodyClient(target);
      let pulled = 0;
      for (const spec of AGENT_SYNC_SPECS) {
        if (opts.agent && spec.id !== opts.agent) continue;
        const data = await client.get(`agents/${spec.id}/${spec.credential.boxRelPath}`);
        if (data === null) continue;
        await mkdir(dirname(spec.credential.hostBackup), { recursive: true });
        await writeFile(spec.credential.hostBackup, data, { mode: 0o600 });
        await chmod(spec.credential.hostBackup, 0o600);
        log.info(`pulled ${spec.id} credentials → ${spec.credential.hostBackup}`);
        pulled++;
      }
      if (pulled === 0) log.info('No agent credentials in custody to pull.');
      else log.success(`Pulled ${String(pulled)} agent credential set(s).`);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const credentialsCmd = new Command('credentials')
  .description('Manage agent credentials on the control box custody store')
  .addCommand(credentialsPushSub)
  .addCommand(credentialsPullSub);

const secretsPushSub = new Command('push')
  .description('Push project secret/env files to the control box custody store')
  .argument('[files...]', 'files to push (default: ./.env if present)')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--project <slug>', 'custody project slug (default: owner__repo, else the directory name)')
  .option('--force', 'upload even when the stored hash matches')
  .action(async (files: string[], opts: { url?: string; project?: string; force?: boolean }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const root = process.cwd();
      const slug = await projectSlug(opts.project, root);
      const chosen = files.length > 0 ? files : existsSync(join(root, '.env')) ? [join(root, '.env')] : [];
      if (chosen.length === 0) {
        log.error('No files to push (no ./.env found; pass files explicitly).');
        process.exitCode = 1;
        return;
      }
      const items: UploadItem[] = [];
      for (const f of chosen) {
        items.push({ path: `projects/${slug}/${basename(f)}`, data: await readFile(f) });
      }
      const client = new CustodyClient(target);
      await pushItems(client, items, `projects/${slug}`, opts.force === true);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const secretsCmd = new Command('secrets')
  .description('Manage per-project secrets/envs on the control box custody store')
  .addCommand(secretsPushSub);

const projectPushSub = new Command('push')
  .description(
    "Push this project's seed material (untracked files + env/secrets) to the control box, so boxes created from its web UI get the files a fresh clone can't provide. A PC create does this automatically; run this to register a project before creating a box from it.",
  )
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--project <slug>', 'custody project slug (default: owner__repo, else the directory name)')
  .option('--force', 'upload even when the stored hash matches')
  .action(async (opts: { url?: string; project?: string; force?: boolean }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const root = (await findProjectRoot(process.cwd())).root;
      const slug = await projectSlug(opts.project, root);
      const res = await pushProjectSeedToCustody({
        controlPlaneUrl: target.url,
        adminToken: target.adminToken,
        slug,
        projectRoot: root,
        // Same default set a create carries into a box, so the seed matches what
        // a PC-created box would have had.
        envPatterns: DEFAULT_ENV_PATTERNS,
        force: opts.force,
        log: (line) => log.info(line),
      });
      const head = res.manifest.repoHeadSha?.slice(0, 8) ?? 'unknown';
      log.success(
        `Pushed ${String(res.uploaded)} item(s), skipped ${String(res.skipped)} unchanged → projects/${slug}/seed (at ${head}).`,
      );
      if (res.skippedTarBytes !== undefined) {
        log.warn(
          `The untracked-files tar (${String(Math.round(res.skippedTarBytes / 1024 / 1024))}MB) exceeded the custody body cap and was NOT pushed — ` +
            'hub-created boxes will miss those files. Raise `relay.custodyMaxBodyBytes` on the control box to include it.',
        );
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const projectCmd = new Command('project')
  .description('Manage a project on the control box (seed material for hub-created boxes)')
  .addCommand(projectPushSub);

const custodyListSub = new Command('list')
  .description('List custody entries (paths + hashes; values are never returned)')
  .argument('[prefix]', 'scope to a prefix, e.g. agents or projects/owner__repo')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .action(async (prefix: string | undefined, opts: { url?: string }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const client = new CustodyClient(target);
      const entries = await client.list(prefix);
      if (entries.length === 0) {
        log.info('No custody entries.');
        return;
      }
      for (const e of entries) {
        process.stdout.write(`${e.path}  ${String(e.size)}B  ${e.sha256.slice(0, 12)}\n`);
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const custodyPullSub = new Command('pull')
  .description('Download a custody scope to a local directory (0600 files)')
  .argument('<scope>', 'custody scope/prefix, e.g. agents, projects/owner__repo, boxes/<id>')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--dest <dir>', 'destination directory (default: ./agentbox-custody)')
  .action(async (scope: string, opts: { url?: string; dest?: string }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const dest = opts.dest ?? join(process.cwd(), 'agentbox-custody');
      const client = new CustodyClient(target);
      const entries = await client.list(scope);
      if (entries.length === 0) {
        log.info(`No custody entries under '${scope}'.`);
        return;
      }
      let pulled = 0;
      for (const e of entries) {
        const data = await client.get(e.path);
        if (data === null) continue;
        const out = join(dest, e.path);
        await mkdir(dirname(out), { recursive: true, mode: 0o700 });
        await writeFile(out, data, { mode: 0o600 });
        await chmod(out, 0o600);
        pulled++;
      }
      log.success(`Pulled ${String(pulled)} entr${pulled === 1 ? 'y' : 'ies'} under '${scope}' to ${dest}.`);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const custodyRmSub = new Command('rm')
  .description('Delete a custody entry (one path) from the control box')
  .argument('<path>', 'custody path, e.g. boxes/<sandboxId>/ssh/id_ed25519 or agents/claude/.credentials.json')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .action(async (path: string, opts: { url?: string }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const res = await fetch(`${target.url}/admin/custody/${path.split('/').map(encodeURIComponent).join('/')}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${target.adminToken}` },
      });
      if (res.status === 204) log.success(`Deleted custody entry '${path}'.`);
      else if (res.status === 404) log.info(`No custody entry at '${path}'.`);
      else {
        log.error(`custody rm failed: ${res.status} ${(await res.text().catch(() => '')).slice(0, 200)}`);
        process.exitCode = 1;
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const custodyCmd = new Command('custody')
  .description('Inspect + download the control box custody store')
  .addCommand(custodyListSub)
  .addCommand(custodyPullSub)
  .addCommand(custodyRmSub);

// --- control-plane box registry (the PC's admin view of the control box) ---

const boxesListSub = new Command('list')
  .description('List boxes registered on the control box')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--json', 'print raw JSON')
  .action(async (opts: { url?: string; json?: boolean }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const client = new ControlPlaneAdminClient(target);
      const [boxes, statuses] = await Promise.all([client.listBoxes(), client.store.listStatuses()]);
      if (opts.json) {
        process.stdout.write(`${JSON.stringify({ boxes, statuses }, null, 2)}\n`);
        return;
      }
      if (boxes.length === 0) {
        log.info('No boxes registered on the control box.');
        return;
      }
      const statusBy = new Map(statuses.map((s) => [s.boxId, s.status]));
      for (const b of boxes) {
        const st = statusBy.get(b.boxId);
        const state = st && typeof st === 'object' && 'state' in st ? String((st as { state?: unknown }).state) : '-';
        process.stdout.write(
          `${b.boxId}  ${b.name}  ${b.kind ?? 'docker'}${b.backend ? `/${b.backend}` : ''}  ${state}\n`,
        );
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const boxesRmSub = new Command('rm')
  .description('Reap a box from the control box (registration + status + SSH-key custody; NOT the cloud resource)')
  .argument('<boxId>', 'the box id as shown by `control-plane boxes list`')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .action(async (boxId: string, opts: { url?: string }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const client = new ControlPlaneAdminClient(target);
      const res = await client.reapBox(boxId);
      if (!res.removed && res.custodyRemoved === 0) {
        log.info(`No box '${boxId}' on the control box.`);
        return;
      }
      log.success(
        `Reaped '${boxId}': registration ${res.removed ? 'removed' : 'absent'}, ` +
          `${String(res.custodyRemoved)} custody file(s) removed. ` +
          `(The cloud resource, if any, is untouched — destroy it from the hub or its provider.)`,
      );
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const boxesCmd = new Command('boxes')
  .description('List + reap boxes registered on the control box')
  .addCommand(boxesListSub)
  .addCommand(boxesRmSub);

// --- control-plane approvals (answerable from the PC) ---

const promptsListSub = new Command('list')
  .description('List pending host-action approvals across control-box boxes')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .option('--json', 'print raw JSON')
  .action(async (opts: { url?: string; json?: boolean }) => {
    try {
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const client = new ControlPlaneAdminClient(target);
      const pending = await client.pendingPrompts();
      if (opts.json) {
        process.stdout.write(`${JSON.stringify(pending, null, 2)}\n`);
        return;
      }
      if (pending.length === 0) {
        log.info('No pending approvals.');
        return;
      }
      for (const p of pending) {
        process.stdout.write(`${p.prompt.id}  [${p.boxName}]  ${p.prompt.message}\n`);
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const promptsAnswerSub = new Command('answer')
  .description('Answer a pending approval on the control box')
  .argument('<id>', 'the prompt id from `control-plane prompts list`')
  .argument('[answer]', 'y | n (default: y)', 'y')
  .option('--url <url>', 'override the control-plane URL (default: relay.controlPlaneUrl)')
  .action(async (id: string, answer: string, opts: { url?: string }) => {
    try {
      if (answer !== 'y' && answer !== 'n') {
        log.error(`answer must be 'y' or 'n' (got '${answer}')`);
        process.exitCode = 1;
        return;
      }
      const target = await resolveCustodyTarget(opts.url);
      if (!target) {
        process.exitCode = 1;
        return;
      }
      const client = new ControlPlaneAdminClient(target);
      const ok = await client.answerPrompt(id, answer);
      if (ok) log.success(`Answered ${id} → ${answer}.`);
      else {
        log.info(`No pending approval with id ${id} (already answered or expired?).`);
        process.exitCode = 1;
      }
    } catch (err) {
      handleLifecycleError(err);
    }
  });

const promptsCmd = new Command('prompts')
  .description('List + answer control-box host-action approvals from the PC')
  .addCommand(promptsListSub)
  .addCommand(promptsAnswerSub);

interface DeployOpts {
  ref?: string;
  repo?: string;
}

// Re-deploy the FULL hub to a fresh Hetzner VPS, REUSING the existing
// ~/.agentbox/control-plane App creds + env — no GitHub-App manifest flow. Pins
// the VPS clone to --ref so a feature branch can be deployed for live verify.
const deployHetznerSub = new Command('hetzner')
  .description('Deploy the full hub to a new Hetzner VPS, reusing the App creds from `control-plane setup`')
  .option('--ref <ref>', 'branch / tag / sha the VPS clones + builds', DEFAULT_DEPLOY_REF)
  .option('--repo <url>', 'git repo the VPS clones', DEFAULT_DEPLOY_REPO)
  .action(async (opts: DeployOpts) => {
    try {
      if (!existsSync(ENV_PATH)) {
        log.error('No control-plane env found. Run `agentbox control-plane setup` first (it creates the GitHub App + admin token).');
        process.exitCode = 1;
        return;
      }
      if (!(await ensureHetznerHubAuth())) {
        log.warn('login prompt cancelled — deploying without web-UI auth.');
      }
      // `--repo` accepts an owner/repo slug or a full git URL; the VPS clones a URL.
      const repoSpec = opts.repo ?? DEFAULT_DEPLOY_REPO;
      const repoUrl = repoSpec.includes('://') ? repoSpec : `https://github.com/${repoSpec}.git`;
      const ds = spinner();
      ds.start('deploying the control box to hetzner');
      let deployedUrl: string;
      try {
        deployedUrl = (
          await runHetznerDeploy({
            envPath: ENV_PATH,
            repoRef: opts.ref ?? DEFAULT_DEPLOY_REF,
            repoUrl,
            log: (line) => ds.message(line),
          })
        ).url;
        ds.stop(`deployed: ${deployedUrl}`);
      } catch (e) {
        ds.stop('deploy failed');
        log.error(e instanceof Error ? e.message : String(e));
        process.exitCode = 1;
        return;
      }
      const url = await applyControlPlaneUrl(deployedUrl);
      log.success(`Pointed the CLI at ${url} (relay.controlPlaneUrl).`);
      const ok = await waitForHealthz(url, 60_000);
      log[ok ? 'success' : 'warn'](
        ok ? `Control box is healthy (${url}/healthz).` : `Could not confirm ${url}/healthz yet — check the deployment.`,
      );
      if (ok) await seedPreparedToNewControlBox(url);
    } catch (err) {
      handleLifecycleError(err);
    }
  });

/**
 * Share this machine's cloud bake records with a freshly-deployed control box,
 * so its first web-UI create boots the base you already baked instead of
 * spending minutes re-baking an identical one. Best-effort: a fresh deploy is
 * still perfectly usable without it (it just bakes on demand).
 */
async function seedPreparedToNewControlBox(url: string): Promise<void> {
  const target = await resolveCustodyTarget(url, { quiet: true });
  if (!target) return;
  const shared: string[] = [];
  for (const provider of SHAREABLE_PREPARED_PROVIDERS) {
    const ok = await pushPreparedToCustody(provider, {
      controlPlaneUrl: target.url,
      adminToken: target.adminToken,
    }).catch(() => false);
    if (ok) shared.push(provider);
  }
  if (shared.length > 0) {
    log.success(`Shared your ${shared.join(', ')} base bake(s) with the control box — it won't re-bake them.`);
  }
}

/**
 * Providers whose base is a provider-side snapshot another machine can boot, so
 * the bake record is worth sharing. Docker is excluded: its base is a local
 * image, rebuilt (or pulled) per machine.
 */
const SHAREABLE_PREPARED_PROVIDERS = ['hetzner', 'vercel', 'e2b', 'daytona', 'digitalocean'] as const;

const deployCmd = new Command('deploy')
  .description('Deploy the full hub to a VPS, reusing the App creds from `control-plane setup`')
  .addCommand(deployHetznerSub);

export const controlPlaneCommand = new Command('control-plane')
  .description('EXPERIMENTAL - Set up + manage the hosted control plane (GitHub App, deploy config, reachability)')
  .addCommand(statusSub, { isDefault: true })
  .addCommand(setupSub)
  .addCommand(deployCmd)
  .addCommand(setUrlSub)
  .addCommand(unsetUrlSub)
  .addCommand(addSub)
  .addCommand(workerSub)
  .addCommand(credentialsCmd)
  .addCommand(secretsCmd)
  .addCommand(projectCmd)
  .addCommand(custodyCmd)
  .addCommand(boxesCmd)
  .addCommand(promptsCmd);
