/**
 * `agentbox install herdr` — generate and link a Herdr plugin
 * (https://herdr.dev/docs/plugins) that adds:
 *   - a boxes-list **overlay** (`prefix+a`) running `agentbox list --herdr --watch`
 *   - a **new box** shortcut (`prefix+shift+a`) opening `agentbox` in a new tab
 *   - a **Ctrl+click** link handler that opens a box's web app (`agentbox://…`)
 *
 * Unlike `install cmux` (which writes a JSON dock entry), we generate the plugin
 * manifest with absolute paths baked into every `command` argv — Herdr runs
 * action/pane commands as a bare argv with **no shell expansion**, so `$PATH` /
 * `$HERDR_BIN_PATH` can't be relied on. The manifest is written to a stable dir
 * under `~/.agentbox` and registered with `herdr plugin link`.
 *
 * Herdr v1 has no sidebar/menu extension point, so the boxes list is an overlay
 * toggled by a key, not a pinned sidebar panel. Herdr's *native* sidebar agent
 * panel (`agent_panel_scope = "all"`) already shows attached boxes globally
 * (phase-1 reports them) — the success note points the user at it.
 */

import { intro, log, note, outro } from '@clack/prompts';
import { Command } from 'commander';
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { AGENTBOX_VERSION } from '../version.js';

/** Directory the generated plugin lives in (stable across package upgrades). */
export function herdrPluginDir(env: NodeJS.ProcessEnv = process.env): string {
  const home = env['AGENTBOX_HOME'] ?? join(homedir(), '.agentbox');
  return join(home, 'herdr', 'plugin');
}

/** The herdr control binary: the in-session path when available, else PATH. */
export function herdrBinary(env: NodeJS.ProcessEnv = process.env): string {
  const b = env['HERDR_BIN_PATH'];
  return b && b.length > 0 ? b : 'herdr';
}

export interface HerdrManifestPaths {
  version: string;
  /** node executable (process.execPath). */
  node: string;
  /** absolute path to the agentbox CLI entry (process.argv[1]). */
  cliEntry: string;
  /** herdr control binary (for the pane-open action). */
  herdrBin: string;
}

/** Format an argv as a TOML array of basic strings (JSON escaping is TOML-safe). */
function tomlArgv(argv: string[]): string {
  return `[${argv.map((a) => JSON.stringify(a)).join(', ')}]`;
}

/**
 * Build the `herdr-plugin.toml` text. Pure — no I/O — so it can be unit-tested.
 * Every command argv is fully resolved (node + CLI entry, or the herdr binary)
 * because Herdr does not shell-expand action commands.
 */
export function buildHerdrManifest(p: HerdrManifestPaths): string {
  const ab = [p.node, p.cliEntry];
  return `# AgentBox Herdr plugin — generated by \`agentbox install herdr\`.
# Do not edit by hand; re-run the command to regenerate.
id = "agentbox"
name = "AgentBox"
version = ${JSON.stringify(p.version)}
min_herdr_version = "0.7.0"
platforms = ["linux", "macos", "windows"]
description = "AgentBox: live boxes overlay, shortcuts, and Ctrl+click to open a box web app."

[[panes]]
id = "boxes"
title = "AgentBox"
placement = "overlay"
command = ${tomlArgv([...ab, 'list', '--herdr', '--watch'])}

[[actions]]
id = "boxes"
title = "AgentBox: boxes overlay"
contexts = ["workspace"]
command = ${tomlArgv([p.herdrBin, 'plugin', 'pane', 'open', '--plugin', 'agentbox', '--entrypoint', 'boxes', '--placement', 'overlay'])}

[[actions]]
id = "new"
title = "AgentBox: new box"
contexts = ["workspace"]
command = ${tomlArgv([...ab, 'herdr', 'new'])}

[[actions]]
id = "link"
title = "AgentBox: open box link"
contexts = ["workspace"]
command = ${tomlArgv([...ab, 'herdr', 'link'])}

[[keys.command]]
key = "prefix+a"
type = "plugin_action"
command = "agentbox.boxes"
description = "AgentBox: boxes overlay"

[[keys.command]]
key = "prefix+shift+a"
type = "plugin_action"
command = "agentbox.new"
description = "AgentBox: new box"

[[link_handlers]]
id = "web"
title = "AgentBox: open box web app"
pattern = "^agentbox://"
action = "link"
`;
}

interface InstallHerdrOptions {
  dryRun?: boolean;
}

export const installHerdrCommand = new Command('herdr')
  .description(
    'Install a Herdr plugin: a boxes-list overlay, keyboard shortcuts, and Ctrl+click to open a box web app.',
  )
  .option('--dry-run', 'print the generated herdr-plugin.toml without writing or linking it')
  .action((opts: InstallHerdrOptions) => {
    const dir = herdrPluginDir();
    const manifest = buildHerdrManifest({
      version: AGENTBOX_VERSION,
      node: process.execPath,
      cliEntry: process.argv[1] ?? 'agentbox',
      herdrBin: herdrBinary(),
    });

    if (opts.dryRun) {
      intro('agentbox install herdr (dry run)');
      process.stdout.write(manifest);
      outro(`would write ${join(dir, 'herdr-plugin.toml')} and run \`herdr plugin link ${dir}\``);
      return;
    }

    mkdirSync(dir, { recursive: true });
    const file = join(dir, 'herdr-plugin.toml');
    writeFileSync(file, manifest);

    intro('AgentBox Herdr plugin');

    // Register (or re-register) the plugin. Best-effort: if `herdr` isn't on
    // PATH (not installed / not in a Herdr session) we still wrote the manifest,
    // so tell the user the one command to run by hand.
    const bin = herdrBinary();
    const linked = spawnSync(bin, ['plugin', 'link', dir], { stdio: 'ignore' });
    if (linked.status === 0) {
      // Pick up the new keybindings/handlers in the running server.
      spawnSync(bin, ['server', 'reload-config'], { stdio: 'ignore' });
    } else {
      log.warn(
        `could not run \`${bin} plugin link\` (is Herdr installed / running?).\n` +
          `Run it yourself:  herdr plugin link ${dir}`,
      );
    }

    note(
      `Wrote ${file}\n` +
        (linked.status === 0 ? `Linked with: herdr plugin link ${dir}\n` : '') +
        '\nShortcuts (under Herdr prefix, default Ctrl+b):\n' +
        '  prefix a        boxes overlay (all boxes)\n' +
        '  prefix shift a  new box in the current project\n' +
        '\nCtrl+click a box name in the overlay to open its web app.\n' +
        '\nTip: set the sidebar agent panel scope to "all" (agent_panel_scope = "all"\n' +
        'in ~/.config/herdr/config.toml, or toggle it in the sidebar) so attached\n' +
        'boxes stay visible when you switch projects.',
      'Installed',
    );
    outro('done');
  });
