export { dockerProvider, type DockerCreateOptions } from './docker-provider.js';
export { providerModule, dockerChecks } from './provider-module.js';
export { downloadFromBox, uploadToBox, type BoxCpResult } from './box-cp.js';
export { createDockerSyncTransport, type DockerSyncTransportInit } from './sync/sync-transport.js';
export { stageItemsFromVolume, volumeSettingsTarget } from './sync/settings-propagate.js';
export { makeDockerSync, type DockerSyncHandle } from './sync/docker-sync.js';

export {
  attachClaudeSession,
  formatDetachNotice,
  buildClaudeAttachArgv,
  buildDashboardAttachArgv,
  buildClaudeLoginRunArgv,
  buildClaudeMounts,
  buildTmuxSessionArgs,
  buildTmuxConfigShellSnippet,
  TERM_FALLBACK_SNIPPET,
  buildShellArgv,
  CLAUDE_FORWARDED_ENV_KEYS,
  ClaudeSessionError,
  claudeSessionInfo,
  CONTAINER_USER,
  DEFAULT_CLAUDE_SESSION,
  ensureClaudeVolume,
  pullClaudeExtras,
  rebuildPluginNativeDeps,
  resolveClaudeVolume,
  runInteractiveClaudeLogin,
  scanPluginCacheForRebuild,
  seedSetupSkillIntoVolume,
  SHARED_CLAUDE_VOLUME,
  startClaudeSession,
  waitForTmuxPaneContent,
  warmUpClaudeCredentials,
  type ClaudeConfigSpec,
  type ClaudeMountResult,
  type ClaudeSessionInfo,
  type EnsureClaudeVolumeOptions,
  type EnsureClaudeVolumeResult,
  type PullClaudeOptions,
  type PullClaudeResult,
  type RebuildPluginNativeDepsResult,
  type StartClaudeSessionOptions,
  type WarmUpClaudeResult,
} from './sync/agents/claude.js';
export {
  CREDENTIALS_BACKUP_FILE,
  CODEX_CREDENTIALS_BACKUP_FILE,
  OPENCODE_CREDENTIALS_BACKUP_FILE,
  hostBackupHasCredentials,
  hostClaudeBackupExpired,
  isRealAgentCredential,
  parseSyncResult,
  parseExtractResult,
  parseVolumeClaudeCredentials,
  volumeClaudeCredentials,
  syncClaudeCredentials,
  extractVolumeAuthToBackup,
  extractCodexCredentials,
  extractOpencodeCredentials,
  type CredentialAgentKind,
  type CredentialSyncDirection,
  type SyncClaudeCredentialsResult,
  type VolumeClaudeCredentials,
} from './sync/claude-credentials.js';
export {
  BOX_SYSTEM_PROMPT_PATH,
  buildCodexAgentsOverrideScript,
  CODEX_OVERRIDE_WROTE_MARKER,
  buildCodexAttachArgv,
  buildCodexLoginRunArgv,
  buildCodexMounts,
  CODEX_FORWARDED_ENV_KEYS,
  CodexSessionError,
  codexSessionInfo,
  DEFAULT_CODEX_SESSION,
  ensureCodexInstalled,
  ensureCodexVolume,
  pullCodexConfig,
  resolveCodexVolume,
  runInteractiveCodexLogin,
  seedCodexAgentsOverride,
  seedCodexHooks,
  SHARED_CODEX_VOLUME,
  startCodexSession,
  volumeHasCodexAuth,
  type CodexConfigSpec,
  type CodexMountResult,
  type CodexSessionInfo,
  type EnsureCodexInstalledResult,
  type EnsureCodexVolumeOptions,
  type EnsureCodexVolumeResult,
  type PullCodexOptions,
  type PullCodexResult,
  type StartCodexSessionOptions,
} from './sync/agents/codex.js';
export {
  buildAgentsMounts,
  ensureAgentsVolume,
  resolveAgentsVolume,
  SHARED_AGENTS_VOLUME,
  type AgentsConfigSpec,
  type AgentsMountResult,
  type EnsureAgentsVolumeOptions,
  type EnsureAgentsVolumeResult,
} from './sync/agents/skills.js';
export {
  buildOpencodeAttachArgv,
  buildOpencodeLoginRunArgv,
  buildOpencodeMounts,
  DEFAULT_OPENCODE_SESSION,
  ensureOpencodeInstalled,
  ensureOpencodeVolume,
  seedOpencodePlugin,
  OPENCODE_FORWARDED_ENV_KEYS,
  OpencodeSessionError,
  opencodeSessionInfo,
  pullOpencodeConfig,
  resolveOpencodeVolume,
  runInteractiveOpencodeLogin,
  SHARED_OPENCODE_VOLUME,
  startOpencodeSession,
  volumeHasOpencodeAuth,
  type EnsureOpencodeInstalledResult,
  type EnsureOpencodeVolumeOptions,
  type EnsureOpencodeVolumeResult,
  type OpencodeConfigSpec,
  type OpencodeMountResult,
  type OpencodeSessionInfo,
  type PullOpencodeOptions,
  type PullOpencodeResult,
  type StartOpencodeSessionOptions,
} from './sync/agents/opencode.js';
export { createBox, type CreateBoxOptions, type CreatedBox } from './create.js';
export {
  agentboxHomeBytes,
  allCheckpointImagesBytes,
  boxResourceStats,
  parseDockerSize,
  projectCheckpointImageBytes,
  volumeSizeBytes,
} from './stats.js';
export { getBoxEndpoints, type BoxEndpoint, type BoxEndpoints } from './endpoints.js';
export { execInBox, removeImage, type DockerExecResult } from './docker.js';
export {
  detectGitRepos,
  GitWorktreeError,
  pickFreshBranch,
  type DetectedGitRepo,
} from './git-worktree.js';
export {
  bindWorktrees,
  collectRepoCarryOver,
  gitWorktreePathFor,
  removeInBoxWorktree,
  seedWorkspace,
  seedWorkspaceFromDir,
  WORKTREE_ROOT,
  type RepoCarryOver,
  type SeedWorkspaceOptions,
  type WorktreeBindSpec,
} from './sync/in-box-git.js';
export {
  DEFAULT_BOX_IMAGE,
  BOX_IMAGE_REGISTRY,
  // The staged build context (Dockerfile.box + the COPY tree). The remote-docker
  // provider tars this and streams it to a remote `docker build -` on a registry
  // miss, so it needs the same context the local build uses.
  BUILD_CONTEXT_DIR,
  DOCKERFILE_PATH,
  registryRefForSha,
  ensureImage,
  classifyDockerBaseFreshness,
  evaluateDockerBaseFreshness,
  type DockerBaseFreshness,
  pullOrBuild,
  pullImage,
  tagImage,
  imageExists,
  imageInfo,
  type ImageInfo,
  type EnsureImageOptions,
  type PullOrBuildOptions,
} from './image.js';
export {
  computeDockerContextFingerprint,
  preparedMatches,
  readPreparedDockerState,
  resolveContextFiles,
  writePreparedDockerState,
  type PreparedDockerState,
  type ResolvedFingerprint,
} from './prepared-state.js';
export { volumeExists } from './docker.js';
export {
  clearRelayNotice,
  DEFAULT_RELAY_PORT,
  ensureRelay,
  forgetBoxFromRelay,
  generateRelayToken,
  getRelayStatus,
  mintHostInitiatedToken,
  registerBoxWithRelay,
  rehydrateRelayRegistry,
  resolveRelayBin,
  RELAY_CONTAINER_NAME,
  RELAY_IMAGE_REF,
  RELAY_NETWORK_NAME,
  setRelayNotice,
  stopRelay,
  type EnsureRelayOptions,
  type RegisterBoxArgs,
  type RelayEndpoint,
  type RelayStatus,
  type StopRelayResult,
} from './relay.js';
export {
  ensureHub,
  getHubStatus,
  resolveHubServer,
  stopHub,
  type EnsureHubOptions,
  type HubEndpoint,
  type HubStatus,
  type StopHubResult,
} from './hub.js';
// The host-config stage producers now live in the provider-neutral sync layer
// (`@agentbox/sandbox-core`); cloud consumers import them from there. The claude
// per-project path helpers + Stage types stay re-exported here (from core) for
// existing `@agentbox/sandbox-docker` importers.
export {
  encodeClaudeProjectsKey,
  resolveClaudeMemoryDir,
  BOX_CLAUDE_PROJECT_DIR,
  type StageClaudeOptions,
  type StageCodexOptions,
  type StageOpencodeOptions,
  type StageResult,
} from '@agentbox/sandbox-core';
export {
  BOX_WORKFLOWS_DIR,
  BOX_MEMORY_DIR,
  BOX_DYNAMIC_SYNC_MANIFEST,
  buildHostSyncManifest,
  computeSyncDelta,
  stageDynamicSyncTarball,
  type DynamicSyncManifest,
  type DynamicSyncSet,
  type DynamicSyncSetName,
  type DynamicSyncDelta,
  type DynamicSyncUpload,
  type DynamicSyncDeletion,
  type HostSyncManifest,
  type StagedTarball,
} from './sync/dynamic-sync.js';
export { EXCLUDE_DIRS, SNAPSHOTS_ROOT, snapshotPathFor } from './snapshot.js';
export {
  CHECKPOINTS_ROOT,
  CHECKPOINT_IMAGE_PREFIX,
  CheckpointError,
  checkpointImageTag,
  computeNextCheckpointName,
  createCheckpoint,
  listAllCheckpointImages,
  listAllCheckpoints,
  listCheckpoints,
  projectCheckpointsDir,
  removeCheckpoint,
  resolveCheckpoint,
  type CheckpointInfo,
  type CheckpointProjectGroup,
  type CheckpointManifest,
  type CheckpointType,
  type CreateCheckpointOptions,
} from './checkpoint.js';
export {
  STATE_DIR,
  STATE_FILE,
  allocateProjectIndex,
  autoPickProjectBox,
  findBox,
  readState,
  recordBox,
  recordLastAgent,
  removeBoxRecord,
  resolveBoxRef,
  type BoxRecord,
  type FindBoxResult,
  type GitWorktreeRecord,
  type StateFile,
} from './state.js';
export {
  attachedContainerUri,
  buildFlavorMounts,
  buildIdeMounts,
  buildVscodeMounts,
  cursorServerVolumeName,
  ensureAgentboxTasksFile,
  ensureIdeVolumes,
  ensureVscodeVolumes,
  ideProfile,
  IDE_FLAVORS,
  ideServerVolumeName,
  repairIdeOwnership,
  repairVscodeServerOwnership,
  SHARED_CURSOR_EXTENSIONS_VOLUME,
  SHARED_VSCODE_EXTENSIONS_VOLUME,
  vscodeServerVolumeName,
  type EnsureTasksFileResult,
  type IdeFlavor,
  type IdeMounts,
  type ServiceTailHint,
  type VscodeMounts,
} from './vscode.js';
export {
  BOXES_ROOT,
  boxRunDirFor,
  boxStatusPathFor,
  readBoxStatus,
  buildHostEnvFindArgs,
  CONTAINER_EXPORT_MERGED,
  copyHostEnvFilesToBox,
  copyHostFilesToBox,
  orbstackVolumePath,
  DEFAULT_ENV_PATTERNS,
  carrySourceHash,
  copyCarryPathsToBox,
  detectEngine,
  getDockerContext,
  ExportError,
  getHostPaths,
  openInFinder,
  pullToHost,
  refreshExport,
  scanHostEnvFiles,
  setEngineOverride,
  type CopyCarryOptions,
  type CopyCarryResult,
  type DockerEngine,
  type HostPaths,
  type CopyHostEnvOptions,
  type CopyHostFilesOptions,
  type OpenOptions,
  type OpenResult,
  type PullOptions,
  type PullResult,
  type RefreshOptions,
  type RefreshResult,
} from './sync/host-export.js';
export {
  detectPortless,
  installPortless,
  portlessBrowserEnv,
  portlessAlias,
  portlessUnalias,
  portlessGetUrl,
  portlessInstallHint,
  portlessStartHint,
  portlessDoctorRow,
  PORTLESS_PROXY_PORT,
  resetPortlessCache,
  resolvePortlessHostStateDir,
  startPortlessProxy,
  startPortlessProxyRoot,
  type PortlessBrowserEnvOptions,
  type PortlessState,
  type RootProxyStartResult,
} from './portless.js';
export {
  AmbiguousBoxError,
  BoxNotFoundError,
  destroyBox,
  getBoxHostPaths,
  inspectBox,
  listBoxes,
  openBoxInFinder,
  pauseBox,
  pruneBoxes,
  refreshBoxSshd,
  resyncBox,
  snapshotPresent,
  startBox,
  stopBox,
  unpauseBox,
  type DestroyOptions,
  type DestroyResult,
  type InspectedBox,
  type ListedBox,
  type OpenedBox,
  type PruneOptions,
  type PruneResult,
  type StartedBox,
} from './lifecycle.js';
export {
  buildVncUrls,
  generateVncPassword,
  launchVncDaemon,
  VNC_CONTAINER_PORT,
  type VncLaunchResult,
  type VncUrls,
} from './vnc.js';
export {
  installAuthorizedKey,
  launchSshdDaemon,
  setUpBoxSshd,
  SSH_CONTAINER_PORT,
  type BoxSshSetup,
  type SshLaunchResult,
} from './ssh.js';
export {
  browserSessionActive,
  ensureBoxBrowser,
  ensureBoxBrowserShowingApp,
  type BoxBrowserAppResult,
  type BoxBrowserResult,
} from './browser.js';
export {
  allocateShellSessionName,
  buildShellSessionAttachArgv,
  DEFAULT_SHELL_SESSION,
  isShellSessionName,
  killShellSession,
  listShellSessions,
  parseShellSessionList,
  SHELL_SESSION_PREFIX,
  shellLabel,
  shellSessionInfo,
  shellSessionName,
  startShellSession,
  type ShellSessionInfo,
  type ShellSessionSummary,
  type StartShellSessionOptions,
} from './shell-session.js';
export {
  dockerVolumeName,
  launchDockerdDaemon,
  SHARED_DOCKER_CACHE_VOLUME,
  type DockerdLaunchResult,
} from './dockerd.js';

// The new `dockerProvider` (implementing the provider-neutral `Provider`
// interface from @agentbox/core) is exported from ./docker-provider.js at the
// top of this file. The CLI resolves it via apps/cli/src/provider/registry.ts.
