export { dockerProvider, type DockerCreateOptions } from './docker-provider.js';
export { downloadFromBox, uploadToBox, type BoxCpResult } from './box-cp.js';

export {
  attachClaudeSession,
  formatDetachNotice,
  buildClaudeAttachArgv,
  buildDashboardAttachArgv,
  buildClaudeLoginRunArgv,
  buildClaudeMounts,
  buildTmuxSessionArgs,
  buildTmuxConfigShellSnippet,
  buildShellArgv,
  CLAUDE_FORWARDED_ENV_KEYS,
  ClaudeSessionError,
  claudeSessionInfo,
  CONTAINER_USER,
  DEFAULT_CLAUDE_SESSION,
  ensureClaudeVolume,
  pullClaudeExtras,
  rebuildPluginNativeDeps,
  resolveClaudeVolume,
  runInteractiveClaudeLogin,
  scanPluginCacheForRebuild,
  seedSetupSkillIntoVolume,
  SHARED_CLAUDE_VOLUME,
  startClaudeSession,
  waitForTmuxPaneContent,
  warmUpClaudeCredentials,
  type ClaudeConfigSpec,
  type ClaudeMountResult,
  type ClaudeSessionInfo,
  type EnsureClaudeVolumeOptions,
  type EnsureClaudeVolumeResult,
  type PullClaudeOptions,
  type PullClaudeResult,
  type RebuildPluginNativeDepsResult,
  type StartClaudeSessionOptions,
  type WarmUpClaudeResult,
} from './claude.js';
export {
  CREDENTIALS_BACKUP_FILE,
  hostBackupHasCredentials,
  parseSyncResult,
  syncClaudeCredentials,
  type CredentialSyncDirection,
  type SyncClaudeCredentialsResult,
} from './claude-credentials.js';
export {
  buildCodexAttachArgv,
  buildCodexLoginRunArgv,
  buildCodexMounts,
  CODEX_FORWARDED_ENV_KEYS,
  CodexSessionError,
  codexSessionInfo,
  DEFAULT_CODEX_SESSION,
  ensureCodexInstalled,
  ensureCodexVolume,
  pullCodexConfig,
  resolveCodexVolume,
  runInteractiveCodexLogin,
  seedCodexHooks,
  SHARED_CODEX_VOLUME,
  startCodexSession,
  volumeHasCodexAuth,
  type CodexConfigSpec,
  type CodexMountResult,
  type CodexSessionInfo,
  type EnsureCodexInstalledResult,
  type EnsureCodexVolumeOptions,
  type EnsureCodexVolumeResult,
  type PullCodexOptions,
  type PullCodexResult,
  type StartCodexSessionOptions,
} from './codex.js';
export {
  buildOpencodeAttachArgv,
  buildOpencodeLoginRunArgv,
  buildOpencodeMounts,
  DEFAULT_OPENCODE_SESSION,
  ensureOpencodeInstalled,
  ensureOpencodeVolume,
  seedOpencodePlugin,
  OPENCODE_FORWARDED_ENV_KEYS,
  OpencodeSessionError,
  opencodeSessionInfo,
  pullOpencodeConfig,
  resolveOpencodeVolume,
  runInteractiveOpencodeLogin,
  SHARED_OPENCODE_VOLUME,
  startOpencodeSession,
  volumeHasOpencodeAuth,
  type EnsureOpencodeInstalledResult,
  type EnsureOpencodeVolumeOptions,
  type EnsureOpencodeVolumeResult,
  type OpencodeConfigSpec,
  type OpencodeMountResult,
  type OpencodeSessionInfo,
  type PullOpencodeOptions,
  type PullOpencodeResult,
  type StartOpencodeSessionOptions,
} from './opencode.js';
export { createBox, type CreateBoxOptions, type CreatedBox } from './create.js';
export {
  agentboxHomeBytes,
  allCheckpointImagesBytes,
  boxResourceStats,
  parseDockerSize,
  projectCheckpointImageBytes,
  volumeSizeBytes,
} from './stats.js';
export { getBoxEndpoints, type BoxEndpoint, type BoxEndpoints } from './endpoints.js';
export { execInBox, removeImage, type DockerExecResult } from './docker.js';
export {
  detectGitRepos,
  GitWorktreeError,
  pickFreshBranch,
  type DetectedGitRepo,
} from './git-worktree.js';
export {
  bindWorktrees,
  collectRepoCarryOver,
  gitWorktreePathFor,
  removeInBoxWorktree,
  seedWorkspace,
  seedWorkspaceFromDir,
  WORKTREE_ROOT,
  type RepoCarryOver,
  type SeedWorkspaceOptions,
  type WorktreeBindSpec,
} from './in-box-git.js';
export {
  DEFAULT_BOX_IMAGE,
  ensureImage,
  imageExists,
  imageInfo,
  type ImageInfo,
} from './image.js';
export {
  computeDockerContextFingerprint,
  preparedMatches,
  readPreparedDockerState,
  resolveContextFiles,
  writePreparedDockerState,
  type PreparedDockerState,
  type ResolvedFingerprint,
} from './prepared-state.js';
export { volumeExists } from './docker.js';
export {
  clearRelayNotice,
  DEFAULT_RELAY_PORT,
  ensureRelay,
  forgetBoxFromRelay,
  generateRelayToken,
  getRelayStatus,
  mintHostInitiatedToken,
  registerBoxWithRelay,
  rehydrateRelayRegistry,
  RELAY_CONTAINER_NAME,
  RELAY_IMAGE_REF,
  RELAY_NETWORK_NAME,
  setRelayNotice,
  stopRelay,
  type EnsureRelayOptions,
  type RegisterBoxArgs,
  type RelayEndpoint,
  type RelayStatus,
  type StopRelayResult,
} from './relay.js';
export {
  stageClaudeStaticForUpload,
  stageClaudeCredentialsForUpload,
  stageCodexStaticForUpload,
  stageCodexCredentialsForUpload,
  stageOpencodeStaticForUpload,
  stageOpencodeCredentialsForUpload,
  stageOpencodeStateForUpload,
  type StageClaudeOptions,
  type StageCodexOptions,
  type StageOpencodeOptions,
  type StageResult,
} from './host-stage.js';
export { EXCLUDE_DIRS, SNAPSHOTS_ROOT, snapshotPathFor } from './snapshot.js';
export {
  CHECKPOINTS_ROOT,
  CHECKPOINT_IMAGE_PREFIX,
  CheckpointError,
  checkpointImageTag,
  computeNextCheckpointName,
  createCheckpoint,
  listAllCheckpointImages,
  listCheckpoints,
  projectCheckpointsDir,
  removeCheckpoint,
  resolveCheckpoint,
  type CheckpointInfo,
  type CheckpointManifest,
  type CheckpointType,
  type CreateCheckpointOptions,
} from './checkpoint.js';
export {
  STATE_DIR,
  STATE_FILE,
  allocateProjectIndex,
  autoPickProjectBox,
  findBox,
  readState,
  recordBox,
  removeBoxRecord,
  resolveBoxRef,
  type BoxRecord,
  type FindBoxResult,
  type GitWorktreeRecord,
  type StateFile,
} from './state.js';
export {
  attachedContainerUri,
  buildFlavorMounts,
  buildIdeMounts,
  buildVscodeMounts,
  cursorServerVolumeName,
  ensureAgentboxTasksFile,
  ensureIdeVolumes,
  ensureVscodeVolumes,
  ideProfile,
  IDE_FLAVORS,
  ideServerVolumeName,
  repairIdeOwnership,
  repairVscodeServerOwnership,
  SHARED_CURSOR_EXTENSIONS_VOLUME,
  SHARED_VSCODE_EXTENSIONS_VOLUME,
  vscodeServerVolumeName,
  type EnsureTasksFileResult,
  type IdeFlavor,
  type IdeMounts,
  type ServiceTailHint,
  type VscodeMounts,
} from './vscode.js';
export {
  BOXES_ROOT,
  boxRunDirFor,
  boxStatusPathFor,
  readBoxStatus,
  buildHostEnvFindArgs,
  CONTAINER_EXPORT_MERGED,
  copyHostEnvFilesToBox,
  copyHostFilesToBox,
  orbstackVolumePath,
  DEFAULT_ENV_PATTERNS,
  detectEngine,
  getDockerContext,
  ExportError,
  getHostPaths,
  openInFinder,
  pullToHost,
  refreshExport,
  scanHostEnvFiles,
  setEngineOverride,
  type DockerEngine,
  type HostPaths,
  type CopyHostEnvOptions,
  type CopyHostFilesOptions,
  type OpenOptions,
  type OpenResult,
  type PullOptions,
  type PullResult,
  type RefreshOptions,
  type RefreshResult,
} from './host-export.js';
export {
  detectPortless,
  installPortless,
  portlessBrowserEnv,
  portlessAlias,
  portlessUnalias,
  portlessGetUrl,
  portlessInstallHint,
  portlessStartHint,
  PORTLESS_PROXY_PORT,
  resetPortlessCache,
  resolvePortlessHostStateDir,
  startPortlessProxy,
  type PortlessBrowserEnvOptions,
  type PortlessState,
} from './portless.js';
export {
  AmbiguousBoxError,
  BoxNotFoundError,
  destroyBox,
  getBoxHostPaths,
  inspectBox,
  listBoxes,
  openBoxInFinder,
  pauseBox,
  pruneBoxes,
  snapshotPresent,
  startBox,
  stopBox,
  unpauseBox,
  type DestroyOptions,
  type DestroyResult,
  type InspectedBox,
  type ListedBox,
  type OpenedBox,
  type PruneOptions,
  type PruneResult,
  type StartedBox,
} from './lifecycle.js';
export {
  buildVncUrls,
  generateVncPassword,
  launchVncDaemon,
  VNC_CONTAINER_PORT,
  type VncLaunchResult,
  type VncUrls,
} from './vnc.js';
export { browserSessionActive, ensureBoxBrowser, type BoxBrowserResult } from './browser.js';
export {
  allocateShellSessionName,
  buildShellSessionAttachArgv,
  DEFAULT_SHELL_SESSION,
  isShellSessionName,
  killShellSession,
  listShellSessions,
  parseShellSessionList,
  SHELL_SESSION_PREFIX,
  shellLabel,
  shellSessionInfo,
  shellSessionName,
  startShellSession,
  type ShellSessionInfo,
  type ShellSessionSummary,
  type StartShellSessionOptions,
} from './shell-session.js';
export {
  dockerVolumeName,
  launchDockerdDaemon,
  SHARED_DOCKER_CACHE_VOLUME,
  type DockerdLaunchResult,
} from './dockerd.js';

// The new `dockerProvider` (implementing the provider-neutral `Provider`
// interface from @agentbox/core) is exported from ./docker-provider.js at the
// top of this file. The CLI resolves it via apps/cli/src/provider/registry.ts.
